"""add embed_keys table

Revision ID: d34700f943d2
Revises: 95b2cac7b7c9
Create Date: 2026-06-16 13:36:00.701537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd34700f943d2'
down_revision: Union[str, None] = '95b2cac7b7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embed_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('allowed_origins', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embed_keys_key'), 'embed_keys', ['key'], unique=True)


def downgrade() -> None:
    op.drop_index(op.f('ix_embed_keys_key'), table_name='embed_keys')
    op.drop_table('embed_keys')
