"""initial schema

Revision ID: e39c96d4d538
Revises: 
Create Date: 2026-06-01 16:21:20.579756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e39c96d4d538'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisers_fb_url'), 'advertisers', ['fb_url'], unique=True)
    op.create_table('geographies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['geographies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'kind', name='uq_geography_name_kind')
    )
    op.create_index(op.f('ix_geographies_name'), 'geographies', ['name'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_celery_task_id'), 'scrape_jobs', ['celery_task_id'], unique=False)
    op.create_table('keyword_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_job_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('location_geography_id', sa.Integer(), nullable=True),
    sa.Column('ads_found', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_geography_id'], ['geographies.id'], ),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_runs_scrape_job_id'), 'keyword_runs', ['scrape_job_id'], unique=False)
    op.create_table('recon_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('found_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recon_findings_advertiser_id'), 'recon_findings', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_recon_findings_source'), 'recon_findings', ['source'], unique=False)
    op.create_table('registry_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('registry', sa.String(length=64), nullable=False),
    sa.Column('registration_number', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('found_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_records_advertiser_id'), 'registry_records', ['advertiser_id'], unique=False)
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advertiser_id', 'url', name='uq_social_link_adv_url')
    )
    op.create_index(op.f('ix_social_links_advertiser_id'), 'social_links', ['advertiser_id'], unique=False)
    op.create_table('social_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=256), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advertiser_id', 'platform', 'handle', name='uq_social_profile')
    )
    op.create_index(op.f('ix_social_profiles_advertiser_id'), 'social_profiles', ['advertiser_id'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('keyword_run_id', sa.Integer(), nullable=True),
    sa.Column('fb_ad_id', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.ForeignKeyConstraint(['keyword_run_id'], ['keyword_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_advertiser_id'), 'ads', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_ads_fb_ad_id'), 'ads', ['fb_ad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_fb_ad_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_advertiser_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_social_profiles_advertiser_id'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_social_links_advertiser_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_registry_records_advertiser_id'), table_name='registry_records')
    op.drop_table('registry_records')
    op.drop_index(op.f('ix_recon_findings_source'), table_name='recon_findings')
    op.drop_index(op.f('ix_recon_findings_advertiser_id'), table_name='recon_findings')
    op.drop_table('recon_findings')
    op.drop_index(op.f('ix_keyword_runs_scrape_job_id'), table_name='keyword_runs')
    op.drop_table('keyword_runs')
    op.drop_index(op.f('ix_scrape_jobs_celery_task_id'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_geographies_name'), table_name='geographies')
    op.drop_table('geographies')
    op.drop_index(op.f('ix_advertisers_fb_url'), table_name='advertisers')
    op.drop_table('advertisers')
    # ### end Alembic commands ###
